services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    expose:
      - "4000"  
    networks:
      projeto-redes-network1:
        ipv4_address: 192.168.0.2  
      projeto-redes-network2:
        ipv4_address: 192.168.1.2  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - ./certs:/etc/nginx/certs  
    ports:
      - "443:443"  
    networks:
      projeto-redes-network1:
        ipv4_address: 192.168.0.3  

  busybox_DB_mockup:
    image: busybox:latest
    command: sleep infinity  
    networks:
      projeto-redes-network2:
        ipv4_address: 192.168.1.3 

networks:
  projeto-redes-network1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24  
  
  projeto-redes-network2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24







